server:
  port: 8081
  servlet:
    context-path: /luckymoney

limit:
  minMoney: 0.01
  maxMoney: 9999
  description: At least ${limit.minMoney} dollars, at most ${limit.maxMoney} dollars.

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/luckymoney
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true